### ISSUE TITLE
Intermittent error after fresh clone and yarn install

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#30]
Repro steps:
* clone
* run yarn install
* in another terminal, run nvm use

Workaround:
- close terminal, reopen, then resume with nvm use

Detailed output:
```
$ nvm use
Found '/home/kanishka/dev/ocamlorg2/.nvmrc' with version <14.15.1>
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at Conf.loadPrefix (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/config/load-prefix.js:46:24)
    at load_ (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/config/core.js:96:5)
    at Conf.emit (events.js:315:20)
    at ConfigChain._resolve (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/config/core.js:338:27)
    at Conf.<anonymous> (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/config/core.js:314:25)
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at process.errorHandler (/home/kanishka/.nvm/versions/node/v14.15.1/lib/node_modules/npm/lib/utils/error-handler.js:183:30)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:156:25) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v14.15.1` to unset it.
```

**Comment by ghost** [comment]
This issue might only occur after deleting a directory, cloning again, while leaving another terminal in that directory. I will watch more closely.

**Comment by ghost** [comment]
Note the symptom in readme and suggest restarting terminal as a workaround.

**Comment by ghost** [comment]
I added `cd .` to recommended commands. That might address the issue when a terminal has the folder deleted from underneath it. I will try to reproduce the error and see if this in fact fixes it.

**Comment by ghost** [comment]
This hasn't occurred in a while. I have been more careful about closing terminal windows after deleting a local clone, so most likely this occurs when a terminal has a stale directory entry. `cd .` should solve that, but the likelihood of anyone encountering this issue is very low, so I won't clutter readme instructions with any tips related to this.
